<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tasks_container_tasks</name>
   <tag></tag>
   <elementGuidId>abc924fc-b36c-43bc-acfc-f71edeb9a2bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#container_tasks</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container_tasks']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>19d523b7-66bf-413f-a660-48a80a6e5262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>container_tasks</value>
      <webElementGuid>84c6ac0d-42b4-49b1-a19d-4ccf383f0d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container_tasks&quot;)</value>
      <webElementGuid>b6795886-3797-4468-8c83-66c9bcb31bee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='container_tasks']</value>
      <webElementGuid>90c40754-12fa-4615-96ef-9bc61716d75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='topnav']/tbody/tr/td[4]/a/div[2]</value>
      <webElementGuid>d20f3c9f-0a9a-4f20-850d-80214dc7ec60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a/div[2]</value>
      <webElementGuid>dd294fdd-370a-4664-a0ea-398da796d621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'container_tasks']</value>
      <webElementGuid>cea2542e-6768-450d-b9c4-657f4125483d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
