<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trainee_pwd</name>
   <tag></tag>
   <elementGuidId>78913f96-0e20-47db-9734-3e8c421f918f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pwd']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pwd&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37ebe51a-c170-4238-af8a-ff1e1a950974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d8fa4279-504e-4c7a-bad4-6922aa9cea7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwd</value>
      <webElementGuid>270c8dbf-86aa-4498-b63f-c2353ae03647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textField pwdfield</value>
      <webElementGuid>85b4bea4-7a14-4d87-b2ab-8008e3cc35f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>c05a1e01-7cd9-4795-8951-b92d97a6f0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginFormContainer&quot;)/tbody[1]/tr[1]/td[@class=&quot;textFieldsArea&quot;]/table[@class=&quot;textFieldsTable&quot;]/tbody[1]/tr[2]/td[1]/input[@class=&quot;textField pwdfield&quot;]</value>
      <webElementGuid>11b8d36d-0ca8-4a31-9b14-d567f57a5ebc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pwd']</value>
      <webElementGuid>d2f74825-a73b-4fd0-8125-df75cfdea1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='loginFormContainer']/tbody/tr/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b1014cea-42e7-4ef5-9b02-2a44e0bc9852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>b338f753-e06e-4514-9598-8b29660b0fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'pwd' and @placeholder = 'Password']</value>
      <webElementGuid>c59209cc-f079-43a9-9c8b-57048941a46c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
