<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Price</name>
   <tag></tag>
   <elementGuidId>56a6da1a-3112-474f-a4a6-9adad63c3006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#c3-mainPanel-price</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='c3-mainPanel-price']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>499a4cbe-a565-47d7-8098-21c429988a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>9a342e2d-de55-45ee-ad8b-7e75ad7e40b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-overlay-aspect </value>
      <webElementGuid>1ccf6d77-a72e-49d0-9125-b41855fb12db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aspecttitle</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>425ad917-33ce-48be-b695-c413ecd8a323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a44a202a-2084-4892-8d0f-5a8d31b09501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>refineOverlay-subPanel</value>
      <webElementGuid>b76a00df-bc33-4971-adef-90d6bdab3e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c3-mainPanel-price</value>
      <webElementGuid>1eafc611-5b06-4932-a746-17ae1c843fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Price</value>
      <webElementGuid>1e71cca0-8a00-4054-ba1d-ed360e9ee79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-mainPanel-price&quot;)</value>
      <webElementGuid>ec99da99-69a3-44d7-ba96-a575c972fd5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='c3-mainPanel-price']</value>
      <webElementGuid>a8482c86-f053-49a1-859e-f9d0d7536ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-mainPanel']/div[23]</value>
      <webElementGuid>c09cb3cd-8346-433a-b254-2dd9c85a185f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]</value>
      <webElementGuid>071269d5-27de-4fec-a4dc-5f1908f41061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'c3-mainPanel-price' and (text() = 'Price' or . = 'Price')]</value>
      <webElementGuid>47a31eb1-f30e-4c97-af7b-463b06a46563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
