<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Screen Size_c3-subPanel-Screen20Size__1d2ff0</name>
   <tag></tag>
   <elementGuidId>9b3307c3-692a-4c64-b9dc-079597550254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='c3-subPanel-Screen%20Size_6%20in%20or%20More_cbx']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5646ab0-e08b-4857-995f-2f91b801d97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>941c0051-5b7c-4479-90b7-587136f08fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c2816553-a520-4a6f-a650-6e3c3910f1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d486ae59-8087-4c07-8d23-de02d01ca704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>c3-subPanel-Screen%20Size_6%20in%20or%20More_cbx</value>
      <webElementGuid>57d50be6-a38c-4e33-ac31-50e28711aefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8427b1c6-4686-4879-af08-b22d8339b311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox__control</value>
      <webElementGuid>79b5d94d-a194-4f0a-a9f7-821febff5dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>30faaab4-d7b3-49ec-b68c-b39c5a8b135b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;c3-subPanel-Screen%20Size_6%20in%20or%20More_cbx&quot;)</value>
      <webElementGuid>1e4ad66c-88b4-4072-a2e1-d768317f076f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='c3-subPanel-Screen%20Size_6%20in%20or%20More_cbx']</value>
      <webElementGuid>100d7b53-6554-48db-90cd-101206907b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='c3-subPanel-Screen%20Size_6%20in%20or%20More']/span/span/input</value>
      <webElementGuid>94f50c37-fd38-4bde-9a83-f2e79261ff97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/span/input</value>
      <webElementGuid>8cc401cf-ff68-4b5b-aaa6-ec4410fe18ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'c3-subPanel-Screen%20Size_6%20in%20or%20More_cbx' and @type = 'checkbox']</value>
      <webElementGuid>7344084f-a584-4da8-8dfe-8f250d5ccc25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
