<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_enal</name>
   <tag></tag>
   <elementGuidId>dfb4ca5b-3e43-4d8c-97d8-3c565f87b37a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sbse11']/div[2]/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>d0976d9a-97c6-4c25-ad97-a193501e7464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>enal</value>
      <webElementGuid>96cc6455-ce3e-46a6-a7c2-780f1bdcbe1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sbse11&quot;)/div[@class=&quot;sbqs_c&quot;]/b[1]</value>
      <webElementGuid>4c92cfb9-9f5f-414f-9a2f-ea8bc97f5907</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sbse11']/div[2]/b</value>
      <webElementGuid>9bb09036-2a1a-4b01-9d46-9d5dd879d946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to queue'])[1]/following::b[1]</value>
      <webElementGuid>8b124109-2447-4142-9d6c-8b1b22ee4577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='enal vs west ham'])[1]/preceding::b[1]</value>
      <webElementGuid>2280d720-aa8e-494d-9c1c-81d26cc1ab8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='enal']/parent::*</value>
      <webElementGuid>8537f367-b0a3-426c-8870-1d75ae3bf54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>a63ab179-f605-464a-b754-87144be9d9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'enal' or . = 'enal')]</value>
      <webElementGuid>cfc70e6c-d859-4922-821a-6134f97f2e04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
