<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>databaseDDT</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>90d2da67-2c58-488f-962e-86994e4041ab</testSuiteGuid>
   <testCaseLink>
      <guid>f0a264c5-23b8-48f8-9526-ed6312527a59</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <iterationNameVariable>
         <defaultValue>''</defaultValue>
         <description></description>
         <id>f1c2d8c2-f18d-42d6-b832-1f6d2fcafcd3</id>
         <masked>false</masked>
         <name>username</name>
      </iterationNameVariable>
      <testCaseId>Test Cases/DataDrivernTesting/ActiTime</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3900af0f-9131-4dbd-82c3-2ee3e0f39552</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/database</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1c2d8c2-f18d-42d6-b832-1f6d2fcafcd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>177d91da-d319-443d-b5d7-a330d69e24b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
