<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>ddt</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6a4e3c02-701a-4666-bca0-65f08813caf4</testSuiteGuid>
   <testCaseLink>
      <guid>d0089cfe-0da2-4b6a-a00c-b2eaf6512591</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DataDrivernTesting/ActiTime</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dfe3b2e9-3400-410c-a849-695d44182e3e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/exceldata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dfe3b2e9-3400-410c-a849-695d44182e3e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>f1c2d8c2-f18d-42d6-b832-1f6d2fcafcd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dfe3b2e9-3400-410c-a849-695d44182e3e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>177d91da-d319-443d-b5d7-a330d69e24b5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
