<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_3 filters applied</name>
   <tag></tag>
   <elementGuidId>907791a8-b423-4e54-91c6-f7166fb12e46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.x-flyout__button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79bcd857-07f3-4845-b8ca-44828b0a95b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-marko</name>
      <type>Main</type>
      <value>{&quot;onclick&quot;:&quot;toggle s0-27_1-9-0-1[0]-0-0-6-5-4[0]-flyout false&quot;}</value>
      <webElementGuid>117bb88e-41f4-4de4-9f0c-5741ad996f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>789998d0-5580-4663-96a0-cf2fa7fa6cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>s0-27_1-9-0-1[0]-0-0-6-5-4[0]-flyout</value>
      <webElementGuid>779d788b-0504-4668-ad1d-15356c8ae56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-flyout__button</value>
      <webElementGuid>d07e78bc-db39-48f8-b890-86e23049a4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7e694505-0aa4-4253-a7f7-8aad677d5101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dcfcb854-9aee-4f52-8b98-689ebf3ad445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>3 filters applied</value>
      <webElementGuid>c8ed401f-1d75-4f53-939a-c3315b6dac92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s0-27_1-9-0-1[0]-0-0-6-5-4[0]-flyout&quot;)/button[@class=&quot;x-flyout__button&quot;]</value>
      <webElementGuid>2dca7bc6-5af2-412c-93fe-22e372badd6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>c041e381-33ba-49c5-9692-b43ec4112c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s0-27_1-9-0-1[0]-0-0-6-5-4[0]-flyout']/button</value>
      <webElementGuid>ccf99e00-5207-423a-ba82-edd94053db92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='filter applied'])[1]/preceding::button[1]</value>
      <webElementGuid>f355aea5-1dbb-49d8-a427-a070b026fd8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/ul/li/div/button</value>
      <webElementGuid>5c727411-b3ea-4406-b869-c579410d241f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '3 filters applied' or . = '3 filters applied')]</value>
      <webElementGuid>bc16e87c-5c33-4c0d-bb71-1fe315ec3891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
