<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Screen Size 6 in or More filter applied</name>
   <tag></tag>
   <elementGuidId>91e7649c-15f4-4680-8a56-e2c032af498b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.brm__item-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='s0-27_1-9-0-1[0]-0-0-6-5-4[0]-flyout']/div/ul/li/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5fb7500d-b037-45ed-8b42-8a5e60b2decd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brm__item-label</value>
      <webElementGuid>b4000e2c-34f0-4d4d-85d7-d2fade4225db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Screen Size: 6 in or More filter applied</value>
      <webElementGuid>83583b64-9bf4-48b4-86c6-f3531f11e564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;s0-27_1-9-0-1[0]-0-0-6-5-4[0]-flyout&quot;)/div[@class=&quot;x-flyout__content flyout-notice flyout-notice--information flyout-notice--top-right&quot;]/ul[@class=&quot;brm__aspect-list&quot;]/li[@class=&quot;brm__aspect-item brm__aspect-item--applied&quot;]/a[1]/span[@class=&quot;brm__item-label&quot;]</value>
      <webElementGuid>010f5240-40d1-407b-a0a7-7a363d67cd0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='s0-27_1-9-0-1[0]-0-0-6-5-4[0]-flyout']/div/ul/li/a/span</value>
      <webElementGuid>34b6bf0f-6d4e-4b9d-bca4-d2baca63e925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Screen Size: 6 in or More']/parent::*</value>
      <webElementGuid>2f93d257-15c7-4dec-a1c9-f5ac8f5c0a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li/a/span</value>
      <webElementGuid>0808e942-fec5-4a78-b9b9-f56a3e48cd56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Screen Size: 6 in or More filter applied' or . = 'Screen Size: 6 in or More filter applied')]</value>
      <webElementGuid>2f6bece4-a7f0-424e-b079-711efc9f2f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
