<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Done</name>
   <tag></tag>
   <elementGuidId>464446e2-257b-46f3-b94c-e489a80a0063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div/div/div/div[5]/div[2]/div[3]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sc-fmciRz.duyTj</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>106acab9-e0e1-49ed-aa5a-bdf5e4a10b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-fmciRz duyTj</value>
      <webElementGuid>0d2bf7ef-09ac-4b84-8fb0-f65cef61009c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>4a506c98-65a0-4c09-8532-0a30260ea9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1gt8xf5-0 cEQQxj&quot;]/div[@class=&quot;sc-1gt8xf5-3 cBVNVf&quot;]/div[@class=&quot;sc-kHOZwM hoZhFj&quot;]/div[@class=&quot;sc-ehCJOs dOUNaZ&quot;]/div[@class=&quot;sc-jUosCB erNlEx&quot;]/div[@class=&quot;sc-lkgTHX abaCA&quot;]/div[@class=&quot;sc-gyElHZ PqRdW&quot;]/a[@class=&quot;sc-fmciRz duyTj&quot;]</value>
      <webElementGuid>1aa7d950-928d-4660-9133-74619cad9008</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div/div[5]/div[2]/div[3]/a[2]</value>
      <webElementGuid>7529f009-e966-41e9-a7da-be8fef8b11f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Done')]</value>
      <webElementGuid>eee7544d-ff4b-4c22-bb97-0b2d392e8752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::a[1]</value>
      <webElementGuid>615d8053-8e63-4ae2-bf3d-b00fd1359580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='first class'])[1]/following::a[2]</value>
      <webElementGuid>9b804f32-64bd-45cd-a9e2-ae2376ebf74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select A Fare Type:'])[1]/preceding::a[1]</value>
      <webElementGuid>68da01e3-f128-4ad8-9ee9-a19624939ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='regular'])[1]/preceding::a[1]</value>
      <webElementGuid>f4d773de-bc5e-4f8d-9a4b-257105f1507d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>e701d44a-27f9-4581-ac07-94a905db170f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>918a41b7-459c-4a6a-aa28-3d13bd7daa24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>0f2f7fea-68cb-414f-a04b-12f4d4999798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
