<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_business</name>
   <tag></tag>
   <elementGuidId>0cb2bfc3-7dcf-4b34-8716-88595d9be0a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div/div/div/div[5]/div[2]/div[2]/div/div[2]/ul/li[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>783fea1a-a03a-4ef4-a4b2-7e99542b9afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-jHkVzv fMjuWe</value>
      <webElementGuid>5ee37c2c-71ce-459d-86ea-c2aec96772d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>business</value>
      <webElementGuid>16770ba5-3764-4383-9a35-e3672cac729a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1gt8xf5-0 cEQQxj&quot;]/div[@class=&quot;sc-1gt8xf5-3 cBVNVf&quot;]/div[@class=&quot;sc-kHOZwM hoZhFj&quot;]/div[@class=&quot;sc-ehCJOs dOUNaZ&quot;]/div[@class=&quot;sc-jUosCB erNlEx&quot;]/div[@class=&quot;sc-lkgTHX abaCA&quot;]/div[@class=&quot;sc-fXeWAj ksETCY&quot;]/div[@class=&quot;sc-fIosxK eskfth&quot;]/div[@class=&quot;sc-kYHfwS fxKxux&quot;]/ul[@class=&quot;sc-dVNjXY Coazc&quot;]/li[@class=&quot;sc-jHkVzv fMjuWe&quot;]</value>
      <webElementGuid>8af50e4f-109c-4da4-b61e-7ec674f24ba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div/div[5]/div[2]/div[2]/div/div[2]/ul/li[3]</value>
      <webElementGuid>f111b988-7859-48b2-80da-25763727b417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='premium economy'])[1]/following::li[1]</value>
      <webElementGuid>0c929a3e-5316-461a-99d8-75c90aafa0f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='economy'])[3]/following::li[2]</value>
      <webElementGuid>22d9cf4e-1617-4a12-8f65-820167e901bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='first class'])[1]/preceding::li[1]</value>
      <webElementGuid>501f82b3-cf1f-4825-bcc1-abc68fcd3bc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::li[2]</value>
      <webElementGuid>55831e7a-bc0a-4b3b-96c0-be4fedf3825c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='business']/parent::*</value>
      <webElementGuid>2deace5a-8f93-4991-892b-5f6caacfd9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[3]</value>
      <webElementGuid>fde6a2de-2e85-4658-86c3-61ecf0aaa802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'business' or . = 'business')]</value>
      <webElementGuid>e63d0005-b724-497b-b2e0-086fde559fe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
