<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Done</name>
   <tag></tag>
   <elementGuidId>330dcd26-07d4-458b-bd38-6ae70d77bc8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div/div/div/div[3]/div[2]/div[3]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.fswTrvl__done</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3478f879-b2b3-413d-8df2-97fb078f0567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>016dd435-f06b-4475-b567-c59e161a9f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fswTrvl__done</value>
      <webElementGuid>7827264a-5fd9-4f64-a853-3eb5d65b6e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Done</value>
      <webElementGuid>db1981c1-7380-48ed-a59b-aee59dcfbd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-1gt8xf5-0 cEQQxj&quot;]/div[@class=&quot;sc-1gt8xf5-3 cBVNVf&quot;]/div[@class=&quot;sc-kHOZwM hoZhFj&quot;]/div[@class=&quot;sc-ehCJOs dOUNaZ&quot;]/div[@class=&quot;sc-jUosCB gpmBju&quot;]/div[@class=&quot;sc-uojGG frgHMT&quot;]/div[@class=&quot;sc-hAcGzb lQuPk&quot;]/span[@class=&quot;fswTrvl__done&quot;]</value>
      <webElementGuid>9b608ef5-7d9d-4eec-bfb5-520afc487c8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div/div[3]/div[2]/div[3]/span[2]</value>
      <webElementGuid>f6b44d1e-03b0-46e3-8fc4-1047ae8884eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[1]</value>
      <webElementGuid>f806404b-e379-42c9-9ca2-d6c8b9b27a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::span[2]</value>
      <webElementGuid>39ef3a31-1d6c-4f03-93de-d9dce9bf9309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return'])[1]/preceding::span[1]</value>
      <webElementGuid>10732463-0e95-4d8a-bbb2-09c0c45a2178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travellers &amp; Class'])[1]/preceding::span[2]</value>
      <webElementGuid>a3aa17d8-fd38-4621-b028-8d99dce5a4a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Done']/parent::*</value>
      <webElementGuid>717332f0-9458-4159-b0ed-14b581b0224a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]</value>
      <webElementGuid>cd8e0938-d78b-4a21-aaa2-95a775dea221</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Done' or . = 'Done')]</value>
      <webElementGuid>4e93fa16-0698-4b74-9613-1a37c1e49336</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
