<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Daily Steal Deals  Special Discounts_l_c0692f</name>
   <tag></tag>
   <elementGuidId>0f71f09b-dcd6-4968-a2fa-9bb0d9a0c2b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.logSprite.icClose</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>73d41d9a-5fe9-4d2c-94d4-990531c8feb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logSprite icClose</value>
      <webElementGuid>c3ced280-1324-4c7b-aff0-dfd4e9fe1aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>20b23ea8-625b-45bf-b8f8-6d4f689bd274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-xayxd-0 ijugDz&quot;]/div[@class=&quot;cm__modalWraper centerMode&quot;]/div[@class=&quot;cm__modal&quot;]/div[@class=&quot;cm__modalContent&quot;]/div[@class=&quot;sc-iCfMLu bctTri&quot;]/div[@class=&quot;sc-furwcr jQTZFO&quot;]/span[@class=&quot;sc-pVTFL gMNQJM&quot;]/span[@class=&quot;logSprite icClose&quot;]</value>
      <webElementGuid>97f67087-86fb-4b35-b6c4-81c15c6696be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/div/div[2]/span/span</value>
      <webElementGuid>13a6059e-9f69-41ee-9a0e-d6be785c41bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span/span</value>
      <webElementGuid>5d52777e-f021-4393-92cf-9bed30b534fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
