<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_trainee_pwd</name>
   <tag></tag>
   <elementGuidId>6d307996-a61a-4019-90b4-c28ad738cc29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pwd&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pwd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ed40f4b-f5c2-4c1b-be3e-63feef078682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c554be9c-9ab7-4553-bd0a-373ddb40e328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwd</value>
      <webElementGuid>003891cd-5dff-4750-99cc-2949ace660f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textField pwdfield</value>
      <webElementGuid>8d96759e-35e0-476e-8522-9557a27e6227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>c181f9c8-3e62-4a9a-a7e0-48abe0167258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginFormContainer&quot;)/tbody[1]/tr[1]/td[@class=&quot;textFieldsArea&quot;]/table[@class=&quot;textFieldsTable&quot;]/tbody[1]/tr[2]/td[1]/input[@class=&quot;textField pwdfield&quot;]</value>
      <webElementGuid>fa35eef7-57b3-4ccb-9d1c-70cc5e8b5235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pwd']</value>
      <webElementGuid>692168e5-d9f5-4cb2-8cc9-84e64b62b2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='loginFormContainer']/tbody/tr/td/table/tbody/tr[2]/td/input</value>
      <webElementGuid>a36a89f9-361d-462f-8884-16995f987946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/input</value>
      <webElementGuid>82ced077-2c93-4c82-a322-b641e01d64b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'pwd' and @placeholder = 'Password']</value>
      <webElementGuid>f5baeadc-b099-48e5-8f0b-d41c7ebe912d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
